CROPS = [
    {
        "name": "Wheat",
        "season": "rabi",
        "water_need": "medium",
        "soil_fit": ["loamy", "clay"],
        "msp": 2275.0,
        "avg_yield": 4.5,
        "has_msp": True,
    },
    {
        "name": "Rice",
        "season": "kharif",
        "water_need": "high",
        "soil_fit": ["clay", "loamy"],
        "msp": 2183.0,
        "avg_yield": 4.0,
        "has_msp": True,
    },
    {
        "name": "Soybean",
        "season": "kharif",
        "water_need": "medium",
        "soil_fit": ["loamy", "sandy"],
        "msp": 4600.0,
        "avg_yield": 1.8,
        "has_msp": True,
    },
    {
        "name": "Onion",
        "season": "rabi",
        "water_need": "low",
        "soil_fit": ["loamy", "sandy"],
        "msp": 0.0,
        "avg_yield": 25.0,
        "has_msp": False,
    },
    {
        "name": "Cotton",
        "season": "kharif",
        "water_need": "medium",
        "soil_fit": ["black", "loamy"],
        "msp": 7121.0,
        "avg_yield": 2.0,
        "has_msp": True,
    },
    {
        "name": "Sugarcane",
        "season": "annual",
        "water_need": "high",
        "soil_fit": ["loamy", "clay"],
        "msp": 340.0,
        "avg_yield": 70.0,
        "has_msp": True,
    },
    {
        "name": "Maize",
        "season": "kharif",
        "water_need": "medium",
        "soil_fit": ["loamy", "sandy", "clay"],
        "msp": 2090.0,
        "avg_yield": 3.5,
        "has_msp": True,
    },
    {
        "name": "Tomato",
        "season": "rabi",
        "water_need": "medium",
        "soil_fit": ["loamy", "sandy"],
        "msp": 0.0,
        "avg_yield": 20.0,
        "has_msp": False,
    },
    {
        "name": "Turmeric",
        "season": "kharif",
        "water_need": "medium",
        "soil_fit": ["loamy", "clay"],
        "msp": 0.0,
        "avg_yield": 6.0,
        "has_msp": False,
    },
    {
        "name": "Chickpea",
        "season": "rabi",
        "water_need": "low",
        "soil_fit": ["loamy", "sandy", "black"],
        "msp": 5440.0,
        "avg_yield": 1.2,
        "has_msp": True,
    },
]

WATER_SCORE = {
    "low": {"low": 1.0, "medium": 0.6, "high": 0.2},
    "medium": {"low": 0.7, "medium": 1.0, "high": 0.5},
    "high": {"low": 0.3, "medium": 0.6, "high": 1.0},
}

SWITCH_RISK = {
    "same": 0.5,
    "similar": 0.8,
    "different": 1.0,
}

SIMILAR_CROPS = {
    "Wheat": ["Chickpea", "Maize"],
    "Rice": ["Maize", "Sugarcane"],
    "Soybean": ["Maize", "Cotton"],
    "Onion": ["Tomato", "Turmeric"],
    "Cotton": ["Soybean", "Maize"],
    "Sugarcane": ["Rice", "Maize"],
    "Maize": ["Wheat", "Soybean"],
    "Tomato": ["Onion", "Turmeric"],
    "Turmeric": ["Onion", "Tomato"],
    "Chickpea": ["Wheat", "Soybean"],
}